project:
  type: website

execute:
  freeze: auto

website:
  title: "Toolkit"
  image: "/images/logo.png"
  favicon: "/images/logo.png"
  search:
    type: overlay  
  page-footer:
    left: |
      © [Jan Kirenz](https://www.kirenz.com/), 2023
    center:
      - text: "Command-line"
        href: cli.qmd
      - text: "SQL"
        href: sql.qmd  
      - text: "Python"
        href: python.qmd
      - text: "GitHub"
        href: github.qmd        
    right:
      - icon: person-circle
        href: https://moodle.hdm-stuttgart.de/login/index.php
        aria-label: Moodle           
  navbar:
    left:
      - href: index.qmd
        text: Home
      - cli.qmd
      - sql.qmd
      - python.qmd
      - github.qmd

format:
  html:
    toc: true
    theme:
      light: [cosmo, theme.scss]
    code-copy: true
    code-overflow: wrap
    css: styles.css